[build]
  base = "/"
  publish = "public/"
  command = "gatsby build"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10"
  # node-gyp が v3.6.0 以上の Python を要求している
  PYTHON_VERSION = "3.8"
